# Generated by Django 5.2.7 on 2025-10-24 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionlog',
            name='bboxes',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='detectionlog',
            name='image_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
